name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        run: |
          echo "My TELEGRAM_BOT_TOKEN is $TELEGRAM_BOT_TOKEN"
          echo "My TELEGRAM_CHAT_ID is $TELEGRAM_CHAT_ID"
